### ISSUE TITLE
Translate xml testcases into our format

### ISSUE THREAD

**Issue by niquola** [lhncbc/fhirpath.js#11]
Write translator for xml use cases into internal yaml format - to be sure we pass all official tests

**Comment by niquola** [comment]
The only problem i see - how to translate xml  resources into json/yaml

**Comment by plynchnlm** [comment]
There is a library for that, with a demo https://fhir-formats.github.io/.  At the moment it only supports STU3, but the author has said he will work on DTSU2.

**Comment by niquola** [comment]
There is standard converter in FHIR distribution written in java and all of ref libraries do this. I'm looking how we can automate it.

**Comment by plynchnlm** [comment]
Okay-- I assigned it to you for now, then.

**Comment by plynchnlm** [comment]
I think this is done.
