### ISSUE TITLE
Proposal: do not support expressions which depends on FHIR metadata

### ISSUE THREAD

**Issue by niquola** [lhncbc/fhirpath.js#15]
In FHIRPath specification (because guys are using code-generated libraries), there are some expressions, which depends on knowledge of FHIR resources structure.
I propose do not support such features in fhirpath.js

* There  are not so much such expressions
* implementation will be much more simpler and non-sensitive to FHIR releases/changes
* more idiomatic for dynamic javascript philosophy

**Comment by plynchnlm** [comment]
I am not sure about the implications of this, but we can certainly start with that support.  However, if these things are extensions that are needed by FHIR, then I don't see how we can avoid writing them, whether in this package or another.
