### ISSUE TITLE
Webpack needs to transpile ES6 code

### ISSUE THREAD

**Issue by plynchnlm** [lhncbc/fhirpath.js#23]
The webpack configuration needs to be revised to transpile the code into something browsers will understand.

**Comment by niquola** [comment]
Do we really need this slow and useless babel for some syntactic sugar?

**Comment by plynchnlm** [comment]
I'm not sure what your point is, but I would like to be able use the modern JavaScript features which are not supported by browsers.  Also, I think the "require" statements we use in node.js require babel processing to run in a browser.

**Comment by plynchnlm** [comment]
I had never heard of performance issues with babel, but after doing some reading I see that there are (or have been) some significant ones.  Performance is important.  We can try coding without ES6 for now.  A shame.  I really like "for...of" and other features, but for...of is not supported by IE 11, which is still ~5% of usage here in the U.S.

**Comment by akanduru** [comment]
I think the main change is use of require. You mentioned above that you are using it somewhere. That may be a bigger change.

**Comment by plynchnlm** [comment]
It turns out that webpack handles that, so "require" is not an issue.
