### ISSUE TITLE
FHIR context should be versioned

### ISSUE THREAD

**Issue by niquola** [lhncbc/fhirpath.js#3]
We need to version FHIR context, because FHIR has a versions which is not compatible back and forth :(

**Comment by plynchnlm** [comment]
Good point.  Do you think there is a need to support old versions like DSTU2, or can we just start with STU3 and R4?

**Comment by niquola** [comment]
let support all versions (dstu2 is used by apple)

**Comment by plynchnlm** [comment]
Closing this, because fhirpath.js does not yet include FHIR type information.
