### ISSUE TITLE
# 5 Functions - list of not implemented functions

### ISSUE THREAD

**Issue by Rende11** [lhncbc/fhirpath.js#46]
## 5. Functions
- [x] 5.2.4. ofType
- [x] 5.4.2. combine
- [x] 5.5.2. toInteger
- [x] 5.5.3. toDecimal
- [x] 5.6.1. indexOf
- [x] 5.6.2. substring
- [x] 5.6.3. startsWith
- [x] 5.6.4. endsWith
- [x] 5.6.5. contains
- [x] 5.6.6. replace
- [x] 5.6.7. matches
- [x] 5.6.8. replaceMatches
- [x] 5.6.9. length
- [x] 5.7.1. children
- [x] 5.7.2. descendants
- [ ] 5.8.2. today
- [ ] 5.8.3. now

**Comment by plynchnlm** [comment]
I think these have now all been implemented.
