### ISSUE TITLE
IE 10 support needed

### ISSUE THREAD

**Issue by plynchnlm** [lhncbc/fhirpath.js#63]
Someone at Cerner told me that EHR systems are still using an IE 10 browser plugin.  Support for Edge is on the way, but it will be about 5 years until 1) the new version is out and 2) customers upgrade to it.

I suspect webpack/babel can handle most issues  for us.

**Comment by niquola** [comment]
we use vanilla js, so it should work in ie. Can they report the errors in
ie?

**Comment by plynchnlm** [comment]
There have not been any reported errors regarding IE 10.  We just need to test and see if it is okay.

**Comment by plynchnlm** [comment]
Confirmed that this is a problem.   Moved issue to https://github.com/HL7/fhirpath.js/issues/8.
